export const changeKeyword = 'changeKeyword'
export const changeGenreId = 'changeGenreId'
export const changeMinPrice = 'changeMinPrice'
export const changeMaxPrice = 'changeMaxPrice'
export const changeSort = 'changeSort'
export const changePage = 'changePage'
export const search = 'search'
